//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Bill
    {
        public string IdBill { get; set; }
        public string IdProduct { get; set; }
        public string Id_Event_sale { get; set; }
        public decimal OriginPrice { get; set; }
        public decimal FinalPrice { get; set; }
        public decimal MoneyTaken { get; set; }
        public decimal MoneyExchange { get; set; }
        public int Amount_Buy { get; set; }
        public int Amount_Given { get; set; }
        public Nullable<decimal> Ship { get; set; }
        public decimal Moneywillget { get; set; }
        public Nullable<decimal> Deposit { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Event_sale Event_sale { get; set; }
        public virtual Product Product { get; set; }
    }
}
